### PR TITLE
tests: lib: docsis.py: check tcl or tcllib installed

### PR DESCRIPTION
**Pull request by lynnlincbn**
Add assert to check tcl or tcllib installed or not.

Signed-off-by: lynn <lynn_lin@compalbn.com>

### CODE REVIEW

**Comment by mattsm** [comment]
Now you need to add Tkinter to requirements.txt

Can we use TKinter to invoke the script instead of os.system as well?

**Comment by mattsm** [comment]
@lynnlincbn please answer questions

**Comment by lynnlincbn** [comment]
1. ok, will update requirements.txt

2.ok, i will try to use TKinter function to run tcl script directly.

**Comment by mattsm** [comment]
@lynnlincbn any updates? I would like to get this merged.

**Comment by lynnlincbn** [comment]
Update to pr_check_tcl_tcllib_installed_v2.
Close it.

**Pull request closed without merging**
