### PR TITLE
tests: lib: docsis.py: check tcl or tcllib installed_v2

### PR DESCRIPTION
**Pull request by lynnlincbn**
1. Add assert to check tcl or tcllib installed or not.
    2. Use TKinter function to run tcl script directly.
    3. For Python 2.7: You don't need to download Tkinter - it's an integral part of all Python distributions

### CODE REVIEW

**Comment by mattsm** [comment]
Shouldn't you remove the old tcl script in the same commit?

**Comment by mattsm** [comment]
@lynnlincbn ?

**Comment by lynnlincbn** [comment]
Sorry, I forgot that, I will commit new patch to remove old tcl, thanks.

**Comment by mattsm** [comment]
It looks like you pushed something new, but did not clean up the old file still?

**Comment by lynnlincbn** [comment]
I'm not sure what did you mean did not clean up the old file still.
I've rm mta_conf.tcl in this commit, can you help to tell me what's wrong on my push, thanks.

tests/lib/mta_conf.tcl
This file was deleted.

**Comment by mattsm** [comment]
Ah, github was trimming the deleted file. I missed it sorry.

**Pull request merged**
