### PR TITLE
devices: openwrt_router: regex fix

### PR DESCRIPTION
**Pull request by mgualco-contractor**
The previouos regex mathed against ip addresses as well.

Signed-off-by: Michele Gualco <mgualco.contractor@libertyglobal.com>

### CODE REVIEW

**Comment by mgualco-contractor** [comment]
the qemu test fails, but on the device the the regex works (and  i have tested it on the regex online for the same values as in the qemmu test and it passes)

**Comment by mattsm** [comment]
Yea that was a fatal error (not related to your change). That happens sometimes with TravisCI.

**Comment by mattsm** [comment]
Yea, but I think this still is not working. What about 

```
diff --git a/devices/openwrt_router.py b/devices/openwrt_router.py
index a8ee2fd..863c05f 100644
--- a/devices/openwrt_router.py
+++ b/devices/openwrt_router.py
@@ -134,7 +134,7 @@ class OpenWrtRouter(base.BaseDevice):
         self.sendcontrol('c')
         self.expect(self.prompt)
         self.sendline('\ncat /proc/uptime')
-        self.expect('((\d+)\.(\d+)(\s)?)((\d+)\.(\d+))?((\d+)\.(\d+))?\r\n')
+        self.expect('((\d+)\.(\d+))((\s)(\d+)\.(\d+))?((\s)(\d+)\.(\d+))?\r\n')
         seconds_up = float(self.match.group(1))
         self.expect(self.prompt)
         return seconds_up
```

**Comment by mgualco-contractor** [comment]
> Yea, but I think this still is not working. What about
> 
> ```
> diff --git a/devices/openwrt_router.py b/devices/openwrt_router.py
> index a8ee2fd..863c05f 100644
> --- a/devices/openwrt_router.py
> +++ b/devices/openwrt_router.py
> @@ -134,7 +134,7 @@ class OpenWrtRouter(base.BaseDevice):
>          self.sendcontrol('c')
>          self.expect(self.prompt)
>          self.sendline('\ncat /proc/uptime')
> -        self.expect('((\d+)\.(\d+)(\s)?)((\d+)\.(\d+))?((\d+)\.(\d+))?\r\n')
> +        self.expect('((\d+)\.(\d+))((\s)(\d+)\.(\d+))?((\s)(\d+)\.(\d+))?\r\n')
>          seconds_up = float(self.match.group(1))
>          self.expect(self.prompt)
>          return seconds_up
> ```

((\d+)\.(\d+))((\s)(\d+)\.(\d+))?((\s)(\d+)\.(\d+))?
matches the IP as well

**Comment by mattsm** [comment]
Ugh, it should be OK with the \r\n - ha

**Comment by mgualco-contractor** [comment]
squashed

**Pull request merged**
