### PR TITLE
tests: lib: docsis: added method to check CM is in briged mode

### PR DESCRIPTION
**Pull request by premandfriends**
-Under cm_cfg class added method "_is_bridged" to check whether CM is in bridge mode

Signed-off-by: prekumar.contractor <prekumar.contractor@libertyglobal.com>

---
This change is [Reviewable](https://reviewable.io/reviews/lgirdk/boardfarm/263)

### CODE REVIEW

**Comment by mattsm** [comment]
@preddy-contractor is this enough to confirm if we are in bridged mode?

**Comment by mattsm** [comment]
Thanks Preddy- what is the default behavior if none are present?

**Comment by mattsm** [comment]
Thanks, @premandfriends can fix the one case at least where eRouter is present and it would be in bridged mode? Thanks.

**Comment by premandfriends** [comment]
Working on the changes. Hoping to update the commit before 29th March

**Comment by mattsm** [comment]
@premandfriends ping... this should be an easy cleanup no?

**Comment by premandfriends** [comment]
This function is enhanced to check all config modes. https://github.com/lgirdk/boardfarm/pull/287

**Comment by mattsm** [comment]
hmm this doesn't look merged, why did it get closed?

**Comment by premandfriends** [comment]
Hi Matthew
The function to check the CM config mode based on Prasada's input is implemented in https://github.com/lgirdk/boardfarm/pull/287 . As the function has become generic and as this thread is related to only bridge, i have closed this thread

**Pull request closed without merging**
