### PR TITLE
deploy-boardfarm-script: add option for static wan node

### PR DESCRIPTION
**Pull request by mattsm**
You can create a static wan node via the following:

$ . ./deploy-boardfarm-nodes.sh
$ set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154 172.16.1.1; set +x
$ ssh root@172.16.1.154

The static ip address and the default gateway are the 2nd and 3rd argument

Signed-off-by: Matthew McClintock <msm-oss@mcclintock.net>

### CODE REVIEW

**Comment by SyHuangCBN** [comment]
When we restart Boardfarm#1, and do command on boardfarm folder.
$ . ./deploy-boardfarm-nodes.sh
 $ set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154 172.16.1.1; set +x
 $ ssh root@172.16.1.154

cbn@cbn-D830MT-2:~/cbn/boardfarm$ docker exec -it bft-node-eth1-wan-shared /bin/bash
root@bft-node-eth1-wan-shared:/# ifconfig eth1
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.1.154  **netmask 255.255.255.255**  broadcast 0.0.0.0
        ether 02:25:7d:ba:1b:b7  txqueuelen 1000  (Ethernet)
        RX packets 344  bytes 34566 (33.7 KiB)
        RX errors 0  dropped 15  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by mattsm** [comment]
Actually you need to do this:

set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154**/24** 172.16.1.1; set +x

Let me fix the commit message.

**Comment by SyHuangCBN** [comment]
depoly

Try to create_container_eth1_static, but still have some problem.

**Comment by mattsm** [comment]
It's better to attach logs not a screen shot. Did you run

. ./deploy-boardfarm-nodes.sh

?

**Comment by SyHuangCBN** [comment]
[Create_container_eth1_static_issue.txt](https://github.com/lgirdk/boardfarm/files/1993810/Create_container_eth1_static_issue.txt)
Even I try to change another branch "pr_add_static_wan" and do the same command.
We have the same problem.

**Comment by mattsm** [comment]
Is the function defined after sourcing that file?

type create_container_eth1_static

**Comment by SyHuangCBN** [comment]
[Create_container_eth1_static_issue_V2.txt](https://github.com/lgirdk/boardfarm/files/1994090/Create_container_eth1_static_issue_V2.txt)

I don't understood what you mean.

**Comment by SyHuangCBN** [comment]
We tried to run command, but it always run another command "create_container_eth1_vlan $vlan"
 ./deploy-boardfarm-nodes.sh create_container_eth1_static 172.16.1.154 172.16.1.1

How to run command correctly to run " create_container_eth1_static " ?

Because we always run "create_container_eth1_vlan $vlan" command

echo "Creating nodes starting on vlan $START_VLAN to $END_VLAN on iface $IFACE"

for vlan in $(seq $START_VLAN $END_VLAN); do
 echo "Creating node on vlan $vlan"
**create_container_eth1_vlan $vlan**

[ "$OPTS" = "both" ] && { local_route; continue; }
if [ $((vlan%2)) -eq 0 ]; then
	[ "$OPTS" = "even" ] && local_route
elif [ "$OPTS" = "odd" ]; then
	local_route
fi


done

**Comment by SyHuangCBN** [comment]
Can you help to check if I missing step
1. Change branch "pr_add_static_wan"
2. change to Boardfarm folder and do command "./deploy-boardfarm-nodes.sh"
3. "set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154/24 172.16.1.1; set +x"
4. "ssh root@172.16.1.154"

But I still can not ping google below

1. docker exec -it bft-node-eth1-wan-shared /bin/bash
2. ping google.com -c1

**Comment by mattsm** [comment]
You are not running the first command correctly (note: the extra dot before, we're just sourcing the command):

mattsm@cbn-D830MT-2:~/git/boardfarm$ . ./deploy-boardfarm-nodes.sh
mattsm@cbn-D830MT-2:~/git/boardfarm$ set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154/24 172.16.1.1; set +x
+ IFACE=eth1
+ create_container_eth1_static wan-shared 172.16.1.154/24 172.16.1.1
+ local name=wan-shared

**Comment by mattsm** [comment]
After that, once you ping out from the container it's globally accessible:

root@bft-node-eth1-wan-shared:/# ping 172.16.1.1
PING 172.16.1.1 (172.16.1.1): 56 data bytes
64 bytes from 172.16.1.1: icmp_seq=0 ttl=255 time=0.834 ms
64 bytes from 172.16.1.1: icmp_seq=1 ttl=255 time=0.883 ms
64 bytes from 172.16.1.1: icmp_seq=2 ttl=255 time=1.052 ms
^C--- 172.16.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.834/0.923/1.052/0.093 ms
root@bft-node-eth1-wan-shared:/# ping google.com
PING google.com (108.177.125.139): 56 data bytes
64 bytes from 108.177.125.139: icmp_seq=0 ttl=45 time=199.502 ms
64 bytes from 108.177.125.139: icmp_seq=1 ttl=45 time=175.588 ms
^C--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 175.588/187.545/199.502/11.957 ms

**Comment by SyHuangCBN** [comment]
I found my problem, missing  space on second dot. ". ./deploy-boardfarm-nodes.sh"
Now everything is correct.

**Pull request merged**
