### PR TITLE
deploy-boardfarm-nodes: Ketan's changes

### PR DESCRIPTION
**Pull request by mgualco-contractor**
moved the default route from eth0 to table 102
on Ketan's behalf

Signed-off-by: Michele Gualco <mgualco.contractor@libertyglobal.com>

### CODE REVIEW

**Comment by mattsm** [comment]
Will connections getting established in from ssh go via this route? E.g. can I still ssh to the container?

**Comment by mattsm** [comment]
@ketantewari please provide answers...

**Comment by ketantewari** [comment]
Yes, we tried it out it works

**Comment by mattsm** [comment]
But then won't basic things fail? Like apt install? Is there a way to force a command to use a specific routing table in Linux?

**Comment by mattsm** [comment]
Holing off on this, since we're discussing using net namespaces instead.

**Pull request closed without merging**
