### PR TITLE
tests: lib: common.py: add firefox options fix error

### PR DESCRIPTION
**Pull request by luketseng**
- error Message: Process unexpectedly closed with status 1
- add firefox options: opts.add_argument("--headless") to fix it

Signed-off-by: luke <luke_tseng@compalbn.com>

### CODE REVIEW

**Comment by luketseng** [comment]
The commit can fix "Process unexpectedly closed with status 1" error message as above.

I have another problem, when run on this commit.
# check environment done, is ok.
$  ./bft -b mv1 -n mv1-3-2
# run ScreenshotGUI script done.
$ ./bft -b mv1 -n mv1-3-2 -e ScreenshotGUI -x connect

The screenshot picture is show "Unable to connect" not show DUT home page(screenshot pic is in result dir). Do you know why?

**Comment by mattsm** [comment]
Why are you forcing me to run headless?

I don't know about this issue.

**Comment by mattsm** [comment]
What is the complete error *without* this change... so we can root cause the issue.

**Comment by luketseng** [comment]
$ ./bft -b mv1 -n mv1-2-2 -e ScreenshotGUI -x connect
==================== Begin ScreenshotGUI ====================
cat /proc/net/vlan/config
VLAN Dev name    | VLAN ID
Name-Type: VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD
eth1           | 102  | eth0
root@bft-node-eth0-102:~# Using proxy 172.16.1.221:8102


=========== Test failed! Running recovery ===========
Message: Process unexpectedly closed with status 1

Traceback (most recent call last):
  File "/home/luke/cbn/boardfarm/tests/linux_boot.py", line 76, in testWrapper
    self.runTest()
  File "/home/luke/cbn/boardfarm/tests/screenshot_gui.py", line 50, in runTest
    driver = lib.common.firefox_webproxy_driver(proxy)
  File "/home/luke/cbn/boardfarm/tests/lib/common.py", line 113, in firefox_webproxy_driver
    driver = webdriver.Firefox(firefox_profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by mattsm** [comment]
But mine works fine:

==================== Begin ScreenshotGUI ====================
cat /proc/net/vlan/config
VLAN Dev name	 | VLAN ID
Name-Type: VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD
eth1           | 102  | eth0
root@bft-node-eth0-102:~# Using proxy 172.16.1.221:8102
taking ss of http://192.168.0.1
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused
recv[RADIUS]: Connection refused

==================== End ScreenshotGUI ======================

**Comment by luketseng** [comment]
...why? I always fail.

==================== Begin ScreenshotGUI ====================
cat /proc/net/vlan/config
VLAN Dev name    | VLAN ID
Name-Type: VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD
eth1           | 102  | eth0
root@bft-node-eth0-102:~# Using proxy 172.16.1.221:8102


=========== Test failed! Running recovery ===========
Message: Process unexpectedly closed with status 1

Traceback (most recent call last):
  File "/home/luke/cbn/boardfarm/tests/linux_boot.py", line 76, in testWrapper
    self.runTest()
  File "/home/luke/cbn/boardfarm/tests/screenshot_gui.py", line 50, in runTest
    driver = lib.common.firefox_webproxy_driver(proxy)
  File "/home/luke/cbn/boardfarm/tests/lib/common.py", line 113, in firefox_webproxy_driver
    driver = webdriver.Firefox(firefox_profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status 1


==================== End ScreenshotGUI ======================

**Comment by luketseng** [comment]
Who can help me?

**Comment by mgualco-contractor** [comment]
> Who can help me?

HI Luke, when I get a minute can give it a go, it did work for me without the headless option (the only thing I needed was the geckodriver visible in my path)

**Comment by mattsm** [comment]
@luketseng you are failing for some reason... maybe you have no display to run on? Does that part install right?

@mgualco-contractor headless at most should only be an option. We want to be able to view what is going on so we can debug it.

**Comment by luketseng** [comment]
I solved it. I just reboot machine. Maybe something program that makes me stuck.

I have another problem, when I run to end.
The screenshot png is show "Unable to connect" not show DUT home page(screenshot pic is in result dir). Do you know why?

**Comment by mattsm** [comment]
If there is an underlying issue we need to get to the bottom of it still.

**Pull request closed without merging**
